packages:
  atuin:
    paths: [ atuin ]
    specfile_path: atuin.spec
    downstream_package_name: atuin
    upstream_package_name: atuin
    actions: &Actions-Package-rust2rpm-workspace
      # Note: in upstream, the License has to be fixed manually after rust2rpm is run
      # Copy from %cargo_license_summary in the build.log
      fix-spec-file:
        - sh -c 'tar -xf ${PACKIT_PROJECT_ARCHIVE}'
        - sh -c 'rust2rpm ./${PACKIT_UPSTREAM_PACKAGE_NAME}-${PACKIT_PROJECT_VERSION}'
        # Note: These should not be automated because workspace packages vary case-by-case and rust2rpm does not support
        #       such automation. Adding simple sed expansion to make it more easily reproduced
        # Patch the license file
        - sh -c 'sed -i "/SourceLicense/{N;N;N;s/.*/cat license.txt/e}" ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
        # Change the default %cargo_install
        - sh -c 'sed -i "s|%cargo_install.*|install -Dpm 0755 target/rpm/atuin -t %{buildroot}%{_bindir}/|" ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
      create-archive:
        - sh -c 'spectool -g -s0 ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
        - sh -c 'echo v${PACKIT_PROJECT_VERSION}.tar.gz'
      get-current-version:
        - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'

  # Other dependencies to package:
  rust-tiny-bip39:
    # https://github.com/maciejhirsz/tiny-bip39/
    paths: [ rust-tiny-bip39 ]
    specfile_path: rust-tiny-bip39.spec
    upstream_package_name: tiny-bip39
    downstream_package_name: rust-tiny-bip39
    actions: &Actions-Package-rust2rpm
      <<: *Actions-Package-rust2rpm-workspace
      fix-spec-file:
        - sh -c 'rust2rpm ${PACKIT_UPSTREAM_PACKAGE_NAME}'
      create-archive: &Create-archive-crate
        - sh -c 'spectool -g -s0 ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
        - sh -c 'echo ${PACKIT_UPSTREAM_PACKAGE_NAME}-${PACKIT_PROJECT_VERSION}.crate'
  rust-interim:
    # https://github.com/conradludgate/interim
    paths: [ rust-interim ]
    specfile_path: rust-interim.spec
    upstream_package_name: interim
    downstream_package_name: rust-interim
    actions: &Actions-Package-no-rust2rpm
      <<: *Actions-Package-rust2rpm
      fix-spec-file: []
  rust-minspan:
    # https://github.com/mwotton/minspan
    paths: [ rust-minspan ]
    specfile_path: rust-minspan.spec
    upstream_package_name: minspan
    downstream_package_name: rust-minspan
    actions: *Actions-Package-rust2rpm
  bash-preexec:
    # https://github.com/rcaloras/bash-preexec
    paths: [ bash-preexec ]
    specfile_path: bash-preexec.spec
    upstream_package_name: bash-preexec
    downstream_package_name: bash-preexec
    actions:
      fix-spec-file: []
      create-archive:
        - sh -c 'echo ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'
      get-current-version:
        - sh -c 'rpmspec -q --qf "%{Version}" --srpm ${PACKIT_DOWNSTREAM_PACKAGE_NAME}.spec'

  # Upstream is working on it:
  rust-crypto_secretbox:
    # https://bugzilla.redhat.com/show_bug.cgi?id=2259330
    # Will probably need to takeover
    paths: [ rust-crypto_secretbox ]
    specfile_path: rust-crypto_secretbox.spec
    upstream_package_name: crypto_secretbox
    downstream_package_name: rust-crypto_secretbox
    actions: *Actions-Package-rust2rpm

srpm_build_deps:
  - rust2rpm

jobs:
  - &copr_build
    job: copr_build
    trigger: pull_request
    owner: lecris
    project: atuin
    targets:
      - fedora-rawhide
    additional_repos:
      - copr://lecris/rust-metrics
      - copr://lecris/rust-sqlx
      - copr://lecris/rust-tonic
  - <<: *copr_build
    trigger: commit
    update_release: false
    owner: sramanujam
    project: atuin
    targets:
      - fedora-all
