[package]
url = "https://atuin.sh"
source-url = "https://github.com/atuinsh/atuin/archive/refs/tags/v%{version}.tar.gz"
extra-files = [
    "%{_datadir}/bash-completion/completions/atuin",
    "%{_datadir}/fish/completions/atuin",
    "%{_datadir}/zsh/site-functions/atuin",
    "%config %{_sysconfdir}/profile.d/atuin.sh"
]

summary = "magical shell history"
cargo-install-lib = true

description = """
Atuin replaces your existing shell history with a SQLite database, and records
additional context for your commands. Additionally, it provides optional and fully
encrypted synchronisation of your history between machines, via an Atuin server.
"""

[requires]
build = [
    "protobuf-devel",
]
test = [
    "postgresql-test-rpm-macros",
]

[scripts.check]
pre = [
    "# start a postgres instance for the tests to use",
    "export PGTESTS_LOCALE=\"C.UTF-8\"",
    "export PGTESTS_USERS=\"atuin:pass\"",
    "export PGTESTS_DATABASES=\"atuin:atuin\"",
    "export PGTESTS_PORT=5432",
    "%postgresql_tests_run"
]

[scripts.install]
post = [
    "# Generate all of the shell-completions",
    "for completion in bash fish zsh; do",
    "  %{buildroot}%{_bindir}/atuin gen-completions --shell $completion -o .",
    "done",
    "install -Dpm 644 atuin.bash %{buildroot}%{_datadir}/bash-completion/completions/atuin",
    "install -Dpm 644 atuin.fish %{buildroot}%{_datadir}/fish/completions/atuin",
    "install -Dpm 644 _atuin %{buildroot}%{_datadir}/zsh/site-functions/atuin",
    "",

    "# Add atuin to default profile",
    "mkdir -p %{buildroot}%{_sysconfdir}/profile.d",

    "cat > %{buildroot}%{_sysconfdir}/profile.d/atuin.sh <<EOF",
    "if [[ \"\\$SHELL\" == \"/bin/bash\" ]]; then",
    "EOF",

    "cat >> %{buildroot}%{_sysconfdir}/profile.d/atuin.sh <<EOF",
    "$(%{buildroot}%{_bindir}/atuin init bash)",
    "EOF",

    "cat >> %{buildroot}%{_sysconfdir}/profile.d/atuin.sh <<EOF",
    "elif [[ \"\\$SHELL\" == \"/bin/zsh\" || \"\\$SHELL\" == \"/usr/bin/zsh\" ]]; then",
    "# The /etc/zprofile calls 'emulate -L ksh', to make zsh happier",
    "# when sourcing files in /etc/profile.d. However, atuin needs",
    "# some zsh-specific functions (i.e. compinit), so we emulate",
    "# for the duration of this if block. Then, 'emulate -L ksh' is",
    "# called once again at the very end.",
    "emulate -L zsh",
    "EOF",

    "cat >> %{buildroot}%{_sysconfdir}/profile.d/atuin.sh <<EOF",
    "$(%{buildroot}%{_bindir}/atuin init zsh)",
    "EOF",

    "cat >> %{buildroot}%{_sysconfdir}/profile.d/atuin.sh <<EOF",
    "# Make sure to go back to emulating ksh after we finish",
    "# initializing atuin.",
    "emulate -L ksh",
    "fi",
    "EOF"
]
