# Generated by rust2rpm 26
%bcond_without check
%global debug_package %{nil}

%global crate parse_duration

Name:           rust-parse_duration
Version:        2.1.1
Release:        %autorelease
Summary:        Parses a duration from a string

License:        MIT
URL:            https://crates.io/crates/parse_duration
Source:         %{crates_source}
# * Bump dependencies
Patch10:       rust-parse_duration-2.1.1-Bump_dependencies.diff

BuildRequires:  cargo-rpm-macros >= 24

%global _description %{expand:
Parses a duration from a string.}

%description %{_description}

%package        devel
Summary:        %{summary}
BuildArch:      noarch

%description    devel %{_description}

This package contains library source intended for building other packages which
use the "%{crate}" crate.

%files          devel
%license %{crate_instdir}/LICENSE
%doc %{crate_instdir}/CHANGELOG.md
%doc %{crate_instdir}/README.md
%{crate_instdir}/

%package     -n %{name}+default-devel
Summary:        %{summary}
BuildArch:      noarch

%description -n %{name}+default-devel %{_description}

This package contains library source intended for building other packages which
use the "default" feature of the "%{crate}" crate.

%files       -n %{name}+default-devel
%ghost %{crate_instdir}/Cargo.toml

%prep
%autosetup -n %{crate}-%{version} -p1
%cargo_prep

%generate_buildrequires
%cargo_generate_buildrequires

%build
%cargo_build

%install
%cargo_install

%if %{with check}
%check
%cargo_test
%endif

%changelog
%autochangelog
